# Generated by Django 2.0rc1 on 2017-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.IntegerField(verbose_name='doctorid')),
                ('doctorkakaoid', models.TextField(max_length=100, verbose_name='doctorkakaoid')),
                ('doctorcount', models.IntegerField(default=0, verbose_name='doctorcount')),
                ('doctorphone', models.TextField(max_length=20, null=True, verbose_name='doctorphone')),
                ('doctorname', models.TextField(max_length=50, null=True, verbose_name='doctorname')),
                ('doctoremail', models.TextField(max_length=50, null=True, verbose_name='doctoremail')),
                ('hospitalname', models.TextField(max_length=50, null=True, verbose_name='hospitalname')),
                ('profileimgurl', models.TextField(max_length=200, null=True, verbose_name='profileimgurl')),
                ('speclist', models.TextField(max_length=500, null=True, verbose_name='speclist')),
                ('schoolname', models.TextField(max_length=50, null=True, verbose_name='schoolname')),
                ('registerdate', models.DateTimeField(auto_now=True, verbose_name='registerdate')),
                ('confirm', models.BooleanField(default=False, verbose_name='confirm')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='userid')),
                ('dataurl', models.TextField(max_length=200, verbose_name='dataurl')),
                ('uploadtime', models.DateTimeField(auto_now=True, verbose_name='uploadtime')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='userid')),
                ('usertoken', models.BigIntegerField(verbose_name='usertoken')),
                ('childname', models.TextField(max_length=50, verbose_name='childname')),
                ('childsex', models.SmallIntegerField(verbose_name='childsex')),
                ('childbirth', models.DateTimeField(verbose_name='childbirth')),
                ('childability', models.SmallIntegerField(verbose_name='childability')),
                ('prevcontent', models.TextField(max_length=200, null=True, verbose_name='prevcontent')),
                ('hopecontent', models.TextField(max_length=200, null=True, verbose_name='hopecontent')),
                ('createdate', models.DateTimeField(auto_now=True, verbose_name='createdate')),
                ('week', models.IntegerField(default=1, verbose_name='week')),
                ('doctorid', models.IntegerField(null=True, verbose_name='doctorid')),
            ],
        ),
        migrations.CreateModel(
            name='Week1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('doctorid', models.IntegerField(verbose_name='doctorid')),
                ('childid', models.IntegerField(verbose_name='childid')),
                ('sender', models.BooleanField(default=False, verbose_name='sender')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='content')),
                ('title', models.TextField(max_length=500, null=True, verbose_name='title')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='date')),
                ('request_type', models.BooleanField(verbose_name='request_type')),
            ],
        ),
        migrations.CreateModel(
            name='Week2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('doctorid', models.IntegerField(verbose_name='doctorid')),
                ('childid', models.IntegerField(verbose_name='childid')),
                ('sender', models.BooleanField(default=False, verbose_name='sender')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='content')),
                ('title', models.TextField(max_length=500, null=True, verbose_name='title')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='date')),
                ('request_type', models.BooleanField(verbose_name='request_type')),
            ],
        ),
        migrations.CreateModel(
            name='Week3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('doctorid', models.IntegerField(verbose_name='doctorid')),
                ('childid', models.IntegerField(verbose_name='childid')),
                ('sender', models.BooleanField(default=False, verbose_name='sender')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='content')),
                ('title', models.TextField(max_length=500, null=True, verbose_name='title')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='date')),
                ('request_type', models.BooleanField(verbose_name='request_type')),
            ],
        ),
        migrations.CreateModel(
            name='Week4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('doctorid', models.IntegerField(verbose_name='doctorid')),
                ('childid', models.IntegerField(verbose_name='childid')),
                ('sender', models.BooleanField(default=False, verbose_name='sender')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='content')),
                ('title', models.TextField(max_length=500, null=True, verbose_name='title')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='date')),
                ('request_type', models.BooleanField(verbose_name='request_type')),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('weekid', models.IntegerField(null=True, verbose_name='weekid')),
                ('weekcontents', models.TextField(max_length=500, verbose_name='weekcontents')),
                ('week_url', models.TextField(max_length=500, verbose_name='week_url')),
                ('week_topic', models.TextField(max_length=500, null=True, verbose_name='week_topic')),
            ],
        ),
    ]
