# Generated by Django 2.0b1 on 2017-11-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAccounts',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False, verbose_name='doctorid')),
                ('doctorcount', models.IntegerField(verbose_name='doctorcount')),
                ('doctorname', models.TextField(max_length=50, verbose_name='doctorname')),
                ('hospitalname', models.TextField(max_length=50, verbose_name='hospitalname')),
                ('profileimgurl', models.TextField(max_length=200, verbose_name='profileimgurl')),
                ('speclist', models.TextField(max_length=500, verbose_name='speclist')),
                ('schoolname', models.TextField(max_length=50, verbose_name='schoolname')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatid', models.AutoField(primary_key=True, serialize=False, verbose_name='treatid')),
                ('week', models.IntegerField(verbose_name='week')),
                ('state', models.SmallIntegerField(verbose_name='state')),
                ('reqdate', models.DateTimeField(verbose_name='reqdate')),
                ('reqcontent', models.TextField(max_length=500, null=True, verbose_name='reqcontent')),
                ('recvdate', models.DateTimeField(null=True, verbose_name='recvdate')),
                ('recvcontent', models.TextField(max_length=500, null=True, verbose_name='recvcontent')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataurl', models.TextField(max_length=200, verbose_name='dataurl')),
                ('uploadtime', models.DateTimeField(auto_now=True, verbose_name='uploadtime')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='userid')),
                ('usertoken', models.BigIntegerField(null=True, verbose_name='usertoken')),
                ('childname', models.TextField(max_length=50, verbose_name='childname')),
                ('childsex', models.SmallIntegerField(verbose_name='childsex')),
                ('childbirth', models.DateTimeField(verbose_name='childbirth')),
                ('childability', models.SmallIntegerField(verbose_name='childability')),
                ('prevcontent', models.TextField(max_length=200, null=True, verbose_name='prevcontent')),
                ('hopecontent', models.TextField(max_length=200, null=True, verbose_name='hopecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('weekid', models.AutoField(primary_key=True, serialize=False, verbose_name='weekid')),
                ('weekcontents', models.TextField(max_length=500, verbose_name='weekcontents')),
            ],
        ),
    ]
