# Generated by Django 2.0b1 on 2017-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='LASTEDIT'),
        ),
    ]
