# Generated by Django 2.0rc1 on 2017-12-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeks',
            name='key',
            field=models.TextField(max_length=100, null=True, verbose_name='key'),
        ),
    ]
