# Generated by Django 2.0b1 on 2017-11-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0002_auto_20171108_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapistName', models.TextField(max_length=20, verbose_name='THERAPISTNAME')),
                ('belongName', models.TextField(max_length=20, verbose_name='BELONGNAME')),
                ('count', models.IntegerField(max_length=10, verbose_name='COUNT')),
                ('belongHospitalName', models.TextField(max_length=20, verbose_name='BELONGHOSPITALNAME')),
                ('specList', models.TextField(max_length=200, verbose_name='SPECLIST')),
                ('profileImageURL', models.TextField(max_length=100, verbose_name='PROFILEIMAGEURL')),
            ],
        ),
    ]
