# Generated by Django 2.0rc1 on 2017-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0002_weeks_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeks',
            name='week_quest',
            field=models.TextField(max_length=500, null=True, verbose_name='week_quest'),
        ),
    ]
