# Generated by Django 2.0b1 on 2017-11-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0003_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='belongHospitalName',
            field=models.TextField(max_length=20, verbose_name='belongHospitalName'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='belongName',
            field=models.TextField(max_length=20, verbose_name='belongName'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='count',
            field=models.IntegerField(max_length=10, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profileImageURL',
            field=models.TextField(max_length=100, verbose_name='profileImageURL'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specList',
            field=models.TextField(max_length=200, verbose_name='specList'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='therapistName',
            field=models.TextField(max_length=20, verbose_name='therapistName'),
        ),
    ]
