# Generated by Django 2.0rc1 on 2017-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recv', '0004_auto_20171119_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.AddField(
            model_name='uploaddatas',
            name='personURL',
            field=models.TextField(max_length=100, null=True, verbose_name='PERSONURL'),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='treeURL',
            field=models.TextField(max_length=100, verbose_name='TREEURL'),
        ),
    ]
